services:
  postgres:
    image: postgres:16.8-alpine
    container_name: flaffee-postgres
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 60s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7.4.3-alpine
    container_name: flaffee-redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

volumes:
  postgres_data: